DROP TABLE IF EXISTS TBL_HEROES;

CREATE TABLE TBL_HEROES
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    heroe_name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
    id LONG AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
)